### ISSUE TITLE
Add DNS records for API server

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/k8s-templates#23]
DNS A record for every API server with cluster name, e.g. k8s.example.com

- [x] Make sure `kind` listens on host port 6443
- [x] Make sure `kind` adds node label with public IP
- [x] Make sure non-`kind` adds node label with public IP
- [x] Make sure `kind` has additional SAN for host IP
- [x] Add `DNSEndpoint` for every `kube-apiserver`
- [x] Add check if `external-dns` is deployed
- [x] Run code after `external-dns` is deployed
- [x] Integrate into `base` deployment
- [ ] Decide whether label name `dille.name/public-ip` is final

**Comment by nicholasdille** [comment]
Read name and IP for kube-apiserver:

```bash
kubectl -n kube-system get pod -l component=kube-apiserver -o name \
| cut -d/ -f2 \
| while read NAME; do \
    IP=$(kubectl -n kube-system get pod $NAME -o json | jq --raw-output '.status.hostIP'); \
    echo $NAME $IP; \
done
```

**Comment by nicholasdille** [comment]
Also requires `kind` configuration to include the appropriate SANs:

```yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
      - k8s.inmylab.de
      - 127.0.0.1
```

**Comment by nicholasdille** [comment]
Create `DNSEndpoints` per master node (requires `external-dns`):

```yaml
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: master1
  namespace: kube-system
spec:
  endpoints:
  - dnsName: k8s.example.com
    recordTTL: 180
    recordType: A
    targets:
    - 10.0.0.1
```
